### ISSUE TITLE
Rename configuration parameters to make it clear what they mean

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/Simod#45]
At the moment, the configuration looks like this:

```yaml
log_path: inputs/PurchasingExample.xes
mining_alg: sm3
exec_mode: optimizer
repetitions: 1
simulation: true
sim_metric: dl
simulator: custom
multitasking: false
structure_optimizer:
  max_eval_s: 2
  concurrency:
    - 0.0
    - 1.0
  epsilon:
    - 0.0
    - 1.0
  eta:
    - 0.0
    - 1.0
  gate_management:
    - equiprobable
    - discovery
  or_rep:
    - true
    - false
  and_prior:
    - true
    - false
time_optimizer:
  max_eval_t: 2
  rp_similarity:
    - 0.5
    - 0.9
  res_dtype:
    - dt247
  arr_dtype:
    - dt247
  res_sup_dis:
    - 0.01
    - 0.3
  res_con_dis:
    - 50
    - 85
  arr_support:
    - 0.01
    - 0.1
  arr_confidence:
    - 1
    - 10
```

There's a lot of names that we can improve, e.g., or_rep, and_priori, rp_similarity, res_dtype, res_cond_dis, etc.
